import { createHash } from "node:crypto";
import type { MaterialKind, SceneSpec } from "./contracts/index.js";

// The seam an external material-generation provider plugs into.
//
// Nothing in this repository generates material. The one provider wired
// below refuses every request, by name and with a reason, so a scene whose
// assets need new material fails its job outright instead of rendering with
// something quietly substituted in. Which providers we may legally use is a
// separate, open question; whatever lands implements `MaterialProvider` and
// is swapped in at the single call site in resolve-scene-assets.ts.
//
// The shape is deliberately narrow:
//
//   * One method. A provider is asked for one asset's bytes and returns
//     them, or throws. There is no batching, no polling handle, and no
//     partial success -- a provider that needs to poll owns that inside
//     `generate`, and a provider that produced three of four assets has
//     failed, because a scene missing an asset cannot be rendered.
//   * Bytes in memory, not a path. The caller owns the filesystem: it
//     decides the workspace layout, the extension, and the artifact upload.
//     A provider that wrote files would have to be trusted with all three.
//   * Provenance returned alongside the bytes, not derived from them.
//     validateSceneSpec rejects a generated asset with no provenance, so
//     the tool, prompt, seed and output hash are part of what a provider
//     owes -- not bookkeeping the caller can invent afterwards. What the
//     caller does instead is *check* it (see produceMaterial): a provider
//     cannot record a hash that is not the hash of the bytes it returned,
//     a prompt other than the one it was given, or another tool's name.
//   * An AbortSignal, because generation happens inside a leased worker
//     phase that can be cancelled.
export type MaterialRequest = Readonly<{
  assetId: string;
  kind: MaterialKind;
  prompt: string;
  // Null when the scene's author recorded no seed. A provider that needs a
  // seed to be reproducible must derive one and record what it used.
  seed: number | null;
  canvas: SceneSpec["canvas"];
}>;

export type MaterialProvenance = Readonly<{
  tool: string;
  prompt: string;
  seed?: number;
  sha256: string;
}>;

export type GeneratedMaterial = Readonly<{
  bytes: Uint8Array;
  contentType: MaterialContentType;
  provenance: MaterialProvenance;
}>;

export type MaterialProvider = Readonly<{
  // Recorded as provenance.tool. Identifies the model/version, so two
  // assets generated by different providers are told apart in the spec.
  tool: string;
  generate(
    request: MaterialRequest,
    signal: AbortSignal,
  ): Promise<GeneratedMaterial>;
}>;

// What the renderer and the artifact store can actually read. Matches
// apps/api's AttachmentContentType, so generated material and an uploaded
// brand attachment travel the same path.
export const MATERIAL_CONTENT_TYPES = [
  "image/png",
  "image/jpeg",
  "image/svg+xml",
  "video/mp4",
  "font/otf",
  "font/ttf",
  "font/woff2",
] as const;
export type MaterialContentType = (typeof MATERIAL_CONTENT_TYPES)[number];
const CONTENT_TYPES: ReadonlySet<string> = new Set(MATERIAL_CONTENT_TYPES);
export const isMaterialContentType = (
  value: string,
): value is MaterialContentType => CONTENT_TYPES.has(value);

export class MaterialGenerationError extends Error {
  readonly token: string;
  readonly assetId: string;
  constructor(token: string, assetId: string, detail = "") {
    super(`${token}:${assetId}${detail ? ` ${detail}` : ""}`);
    this.name = "MaterialGenerationError";
    this.token = token;
    this.assetId = assetId;
  }
}

// The only provider wired today. Deterministic in the only sense that
// matters here: it refuses the same way every time, for every asset, and
// says which asset it refused and why. This is the fail-closed stance
// apps/api/src/safety-check.ts takes -- an unavailable capability fails the
// job; it never degrades into a placeholder.
export const unavailableMaterialProvider: MaterialProvider = {
  tool: "none",
  generate: async (request) => {
    throw new MaterialGenerationError(
      "MATERIAL_PROVIDER_UNAVAILABLE",
      request.assetId,
      "no material-generation provider is configured for this deployment",
    );
  },
};

// Narrows a real provider to the one kind it actually handles, refusing
// every other kind through `fallback` (the fail-closed stub by default)
// instead of letting it silently attempt -- or silently succeed at -- a
// kind it was never built for. This is how the image provider gets wired
// in without widening what video or font material can do: each lands as
// its own `restrictToKind` call, composed alongside the others, so an
// unimplemented kind keeps failing closed rather than falling through to
// whichever provider happens to run last.
//
// `tool` forwards to the underlying provider's `tool` rather than copying
// it once at construction time, because a provider whose identity is only
// known after a call completes (see remote-image-material-provider.ts)
// needs produceMaterial's post-`generate()` read of `.tool` to see the
// up-to-date value.
export function restrictToKind(
  kind: MaterialKind,
  provider: MaterialProvider,
  fallback: MaterialProvider = unavailableMaterialProvider,
): MaterialProvider {
  // Tracks which of the two actually handled the most recent request, so
  // the `tool` getter reflects whichever one produceMaterial is about to
  // check -- not always `provider`, which would misreport a request the
  // fallback served instead.
  let active: MaterialProvider = provider;
  return {
    get tool() {
      return active.tool;
    },
    generate: (request, signal) => {
      active = request.kind === kind ? provider : fallback;
      return active.generate(request, signal);
    },
  };
}

// Asks a provider for one asset's material and refuses to believe it
// without checking. Everything a generated asset's provenance claims is
// verified here, because the spec that goes on to be rendered carries this
// provenance as fact.
export async function produceMaterial(
  provider: MaterialProvider,
  request: MaterialRequest,
  signal: AbortSignal,
): Promise<GeneratedMaterial> {
  const material = await provider.generate(request, signal);
  if (material.bytes.byteLength === 0)
    throw new MaterialGenerationError("MATERIAL_EMPTY", request.assetId);
  if (!isMaterialContentType(material.contentType))
    throw new MaterialGenerationError(
      "MATERIAL_CONTENT_TYPE_INVALID",
      request.assetId,
      material.contentType,
    );
  const sha256 = createHash("sha256").update(material.bytes).digest("hex");
  if (
    material.provenance.sha256 !== sha256 ||
    material.provenance.prompt !== request.prompt ||
    material.provenance.tool !== provider.tool
  )
    throw new MaterialGenerationError(
      "MATERIAL_PROVENANCE_MISMATCH",
      request.assetId,
    );
  return material;
}
