import { createHash } from "node:crypto";
import type {
  MaterialKind,
  SceneSpec,
  SpecAssetForm,
} from "./contracts/index.js";

// The seam an external material-generation provider plugs into.
//
// Nothing in this repository generates material. The one provider wired
// below refuses every request, by name and with a reason, so a scene whose
// assets need new material fails its job outright instead of rendering with
// something quietly substituted in. Which providers we may legally use is a
// separate, open question; whatever lands implements `MaterialProvider` and
// is swapped in at the single call site in resolve-scene-assets.ts.
//
// The shape is deliberately narrow:
//
//   * One method. A provider is asked for one asset's bytes and returns
//     them, or throws. There is no batching, no polling handle, and no
//     partial success -- a provider that needs to poll owns that inside
//     `generate`, and a provider that produced three of four assets has
//     failed, because a scene missing an asset cannot be rendered.
//   * Bytes in memory, not a path. The caller owns the filesystem: it
//     decides the workspace layout, the extension, and the artifact upload.
//     A provider that wrote files would have to be trusted with all three.
//   * Provenance returned alongside the bytes, not derived from them.
//     validateSceneSpec rejects a generated asset with no provenance, so
//     the tool, prompt, seed and output hash are part of what a provider
//     owes -- not bookkeeping the caller can invent afterwards. What the
//     caller does instead is *check* it (see produceMaterial): a provider
//     cannot record a hash that is not the hash of the bytes it returned,
//     a prompt other than the one it was given, or another tool's name.
//   * An AbortSignal, because generation happens inside a leased worker
//     phase that can be cancelled.
export type MaterialRequest = Readonly<{
  assetId: string;
  kind: MaterialKind;
  prompt: string;
  // Null when the scene's author recorded no seed. A provider that needs a
  // seed to be reproducible must derive one and record what it used.
  seed: number | null;
  // How the scene asked for this material to be made: "flat" for a 2D
  // generation, "object" for a rendered three-dimensional thing. Always
  // present -- planSceneAssets normalises an absent field to "flat" -- so
  // createMaterialProvider never has to re-decide what a missing value
  // meant. Distinct from `kind`, which is what the renderer draws: an
  // object-form request still comes back as an image.
  form: SpecAssetForm;
  canvas: SceneSpec["canvas"];
}>;

export type MaterialProvenance = Readonly<{
  tool: string;
  prompt: string;
  seed?: number;
  sha256: string;
}>;

export type GeneratedMaterial = Readonly<{
  bytes: Uint8Array;
  contentType: MaterialContentType;
  provenance: MaterialProvenance;
}>;

export type MaterialProvider = Readonly<{
  // Recorded as provenance.tool. Identifies the model/version, so two
  // assets generated by different providers are told apart in the spec.
  tool: string;
  generate(
    request: MaterialRequest,
    signal: AbortSignal,
  ): Promise<GeneratedMaterial>;
}>;

// What the renderer and the artifact store can actually read. Matches
// apps/api's AttachmentContentType, so generated material and an uploaded
// brand attachment travel the same path.
export const MATERIAL_CONTENT_TYPES = [
  "image/png",
  "image/jpeg",
  "image/svg+xml",
  "video/mp4",
  "font/otf",
  "font/ttf",
  "font/woff2",
] as const;
export type MaterialContentType = (typeof MATERIAL_CONTENT_TYPES)[number];
const CONTENT_TYPES: ReadonlySet<string> = new Set(MATERIAL_CONTENT_TYPES);
export const isMaterialContentType = (
  value: string,
): value is MaterialContentType => CONTENT_TYPES.has(value);

export class MaterialGenerationError extends Error {
  readonly token: string;
  readonly assetId: string;
  constructor(token: string, assetId: string, detail = "") {
    super(`${token}:${assetId}${detail ? ` ${detail}` : ""}`);
    this.name = "MaterialGenerationError";
    this.token = token;
    this.assetId = assetId;
  }
}

// The only provider wired today. Deterministic in the only sense that
// matters here: it refuses the same way every time, for every asset, and
// says which asset it refused and why. This is the fail-closed stance
// apps/api/src/safety-check.ts takes -- an unavailable capability fails the
// job; it never degrades into a placeholder.
export const unavailableMaterialProvider: MaterialProvider = {
  tool: "none",
  generate: async (request) => {
    throw new MaterialGenerationError(
      "MATERIAL_PROVIDER_UNAVAILABLE",
      request.assetId,
      "no material-generation provider is configured for this deployment",
    );
  },
};

export type MaterialProviderFactoryOptions = Readonly<{
  requestImage?: (
    request: MaterialRequest,
    signal: AbortSignal,
  ) => Promise<GeneratedMaterial>;
  object?: MaterialProvider;
  video?: MaterialProvider;
}>;

// Routes one request to the provider that owns that kind/form. Image+object
// is Hi3DGen+Blender; other images go through the API relay (`requestImage`);
// video is Wan-Alpha; everything else fails closed.
export function createMaterialProvider(
  options: MaterialProviderFactoryOptions,
): MaterialProvider {
  let imageTool = "unset";
  const image: MaterialProvider | undefined =
    options.requestImage === undefined
      ? undefined
      : {
          get tool() {
            return imageTool;
          },
          generate: async (request, signal) => {
            const requestImage = options.requestImage;
            if (requestImage === undefined)
              throw new MaterialGenerationError(
                "MATERIAL_PROVIDER_UNAVAILABLE",
                request.assetId,
              );
            const material = await requestImage(request, signal);
            imageTool = material.provenance.tool;
            return material;
          },
        };
  let active: MaterialProvider =
    image ??
    options.object ??
    options.video ??
    unavailableMaterialProvider;
  return {
    get tool() {
      return active.tool;
    },
    generate: (request, signal) => {
      if (request.kind === "image" && request.form === "object")
        active = options.object ?? unavailableMaterialProvider;
      else if (request.kind === "image")
        active = image ?? unavailableMaterialProvider;
      else if (request.kind === "video")
        active = options.video ?? unavailableMaterialProvider;
      else active = unavailableMaterialProvider;
      return active.generate(request, signal);
    },
  };
}

// Asks a provider for one asset's material and refuses to believe it
// without checking. Everything a generated asset's provenance claims is
// verified here, because the spec that goes on to be rendered carries this
// provenance as fact.
export async function produceMaterial(
  provider: MaterialProvider,
  request: MaterialRequest,
  signal: AbortSignal,
): Promise<GeneratedMaterial> {
  const material = await provider.generate(request, signal);
  if (material.bytes.byteLength === 0)
    throw new MaterialGenerationError("MATERIAL_EMPTY", request.assetId);
  if (!isMaterialContentType(material.contentType))
    throw new MaterialGenerationError(
      "MATERIAL_CONTENT_TYPE_INVALID",
      request.assetId,
      material.contentType,
    );
  const sha256 = createHash("sha256").update(material.bytes).digest("hex");
  if (
    material.provenance.sha256 !== sha256 ||
    material.provenance.prompt !== request.prompt ||
    material.provenance.tool !== provider.tool
  )
    throw new MaterialGenerationError(
      "MATERIAL_PROVENANCE_MISMATCH",
      request.assetId,
    );
  return material;
}
