import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { deriveMaterialSeed } from "./material-seed.js";
import {
  MaterialGenerationError,
  type MaterialProvider,
} from "./material-provider.js";
import { runCommand, type CommandRunner } from "./process-runner.js";

// The worker's other new self-hosted provider: Hi3DGen (chosen, per the
// task's briefing, specifically because it drops the NVIDIA `nvdiffrast`
// dependency that makes TRELLIS commercially unusable) plus a headless
// Blender render, both reachable only on worker-internal -- same
// direct-call, no-relay, no-internet shape as the video provider in
// self-hosted-video-material-provider.ts.
//
// Hi3DGen produces geometry only, no texture -- its job ends at a mesh.
// This provider's job is everything after that: give the mesh a material
// and lighting, put a camera in front of it, and render one still. That
// render is an ordinary `image`-kind asset (PNG, alpha channel from
// `film_transparent`), which is the one asset kind the renderer already
// draws in full today (render-app/generated.ts's image branch) -- unlike
// video-kind material, this needs no future renderer work to be usable.
//
// This is why it is wired as an *alternative* backend for the existing
// `image` MaterialKind (see index.ts) rather than a kind of its own: the
// scene-asset contract (apps/worker/src/contracts/scene-assets.ts) has
// exactly three material kinds -- image, video, font -- and both this
// provider and the 2D one hand back a PNG the renderer draws as an image,
// so a kind that said "3d model" would be a lie in the type.
//
// Which of the two answers a given `image` request is now a per-asset
// decision the scene makes: SpecAsset's `form` field ("flat" or
// "object"), routed by restrictToForm in index.ts. An object-form asset
// comes here; everything else goes to the OpenAI relay, exactly as before.
// Leaving RVS_HI3DGEN_BASE_URL unset keeps that relay path completely
// unchanged and makes an object-form asset fail by name below, rather than
// silently getting a flat picture of something the scene asked to be a
// physical object.
export const HI3DGEN_BLENDER_TOOL = "hi3dgen+blender-cycles-cpu-spp128@1";

// Cycles is not bit-identical across CPU, CUDA and OptiX, and its denoiser
// adds further hardware dependence (the task's own briefing) -- unlike the
// video and image providers, Blender renders the frame itself rather than
// handing back a vendor's already-generated bytes, so this determinism
// risk is this provider's alone to manage. Pinned here, exactly once, in
// buildBlenderScript below:
//   - compute device: CPU only, never CUDA/OptiX. Removes cross-GPU-
//     vendor/driver variance entirely; the deployment either has Blender
//     available or it doesn't; when it does, it renders the same way on
//     every host, GPU or not.
//   - render threads: fixed at 1. Cycles' per-pixel RNG is seeded from
//     pixel coordinates and shouldn't need this, but nothing here has been
//     verified against a live Blender, so the more defensible, fully
//     serial choice is the one made.
//   - sample count: fixed (BLENDER_SAMPLES below), adaptive sampling off.
//   - denoiser: off.
//   - seed: request.seed, or one this provider derives (material-seed.ts)
//     when the scene names none -- the same rule the video provider
//     follows.
// All of this is named in HI3DGEN_BLENDER_TOOL ("cycles-cpu-spp128") so
// it is visible in provenance without a schema change, but none of it has
// been run against a real Blender binary -- there is no Blender in this
// environment (nor a GPU, nor a reachable Hi3DGen instance). The pinning
// choices are principled, not confirmed; see the implementation report.
export const BLENDER_SAMPLES = 128;

// The self-hosted service's own HTTP contract, as documented to me --
// nothing here has been exercised against a running Hi3DGen instance.
// Isolated behind this one injectable function, same shape as the video
// provider's WanAlphaClient. Returns raw, untextured mesh bytes (assumed
// glTF binary -- a format Blender's own importer reads natively).
export type Hi3DGenClient = (
  baseUrl: string,
  request: Readonly<{ prompt: string; seed: number }>,
  signal: AbortSignal,
) => Promise<Uint8Array>;

const defaultHi3DGenClient: Hi3DGenClient = async (
  baseUrl,
  request,
  signal,
) => {
  const response = await fetch(`${baseUrl.replace(/\/+$/u, "")}/v1/generate`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ prompt: request.prompt, seed: request.seed }),
    signal,
  });
  if (!response.ok)
    throw new Error(`HI3DGEN_REQUEST_FAILED:${response.status}`);
  return new Uint8Array(await response.arrayBuffer());
};

export type SelfHosted3DMaterialProviderConfig = Readonly<{
  // Undefined means "not configured" -- generate() then refuses by name,
  // the same fail-closed stance unavailableMaterialProvider takes.
  baseUrl: string | undefined;
  blenderPath?: string;
  samples?: number;
  runCommand?: CommandRunner;
  client?: Hi3DGenClient;
}>;

// A single, static script -- every run-specific value (mesh path, output
// path, canvas size, seed, sample count) travels through the JSON args
// file instead of being interpolated into the script text, so the script
// itself never changes between assets and is trivial to inspect (see
// self-hosted-3d-material-provider.test.ts's "pins ..." assertions).
export function buildBlenderScript(): string {
  return `import bpy
import json
import sys

argv = sys.argv[sys.argv.index("--") + 1:]
with open(argv[0], "r", encoding="utf-8") as handle:
    cfg = json.load(handle)

bpy.ops.wm.read_factory_settings(use_empty=True)
bpy.ops.import_scene.gltf(filepath=cfg["meshPath"])

# Hi3DGen produces geometry only -- give every imported mesh a plain,
# neutral material so it has something to catch light with.
material = bpy.data.materials.new("rvs_material")
material.use_nodes = True
bsdf = material.node_tree.nodes.get("Principled BSDF")
bsdf.inputs["Base Color"].default_value = (0.72, 0.72, 0.72, 1.0)
bsdf.inputs["Roughness"].default_value = 0.5
for obj in bpy.context.scene.objects:
    if obj.type == "MESH":
        obj.data.materials.clear()
        obj.data.materials.append(material)


def add_light(name, kind, location, energy):
    light_data = bpy.data.lights.new(name=name, type=kind)
    light_data.energy = energy
    light_obj = bpy.data.objects.new(name=name, object_data=light_data)
    bpy.context.collection.objects.link(light_obj)
    light_obj.location = location


add_light("key", "AREA", (4, -4, 5), 1000)
add_light("fill", "AREA", (-4, -2, 3), 400)
add_light("rim", "AREA", (0, 4, 4), 600)

camera_data = bpy.data.cameras.new("camera")
camera = bpy.data.objects.new("camera", camera_data)
bpy.context.collection.objects.link(camera)
camera.location = (0, -6, 3)
camera.rotation_euler = (1.1, 0, 0)
bpy.context.scene.camera = camera

scene = bpy.context.scene
scene.render.engine = "CYCLES"
# Pinned for determinism -- see HI3DGEN_BLENDER_TOOL's doc comment in
# self-hosted-3d-material-provider.ts for why each of these is fixed.
scene.cycles.device = "CPU"
scene.cycles.seed = cfg["seed"]
scene.cycles.samples = cfg["samples"]
scene.cycles.use_adaptive_sampling = False
scene.cycles.use_denoising = False
scene.render.threads_mode = "FIXED"
scene.render.threads = 1
scene.render.resolution_x = cfg["width"]
scene.render.resolution_y = cfg["height"]
scene.render.resolution_percentage = 100
scene.render.film_transparent = True
scene.render.image_settings.file_format = "PNG"
scene.render.image_settings.color_mode = "RGBA"
scene.render.filepath = cfg["outputPath"]

bpy.ops.render.render(write_still=True)
`;
}

const PNG_SIGNATURE = Uint8Array.from([137, 80, 78, 71, 13, 10, 26, 10]);

// Verifies the rendered PNG is actually the shape asked for -- the same
// kind of "check, don't just trust" QC gen-render-delivery.ts's ffprobe
// validation and openai-image-material.ts's IHDR check both do -- before
// this provider hands it back as the finished asset.
function readPngIhdr(
  bytes: Uint8Array,
): Readonly<{ width: number; height: number; colorType: number }> | null {
  if (bytes.byteLength < 33) return null;
  for (let index = 0; index < PNG_SIGNATURE.length; index += 1)
    if (bytes[index] !== PNG_SIGNATURE[index]) return null;
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const chunkType = String.fromCharCode(...bytes.subarray(12, 16));
  if (chunkType !== "IHDR") return null;
  return {
    width: view.getUint32(16),
    height: view.getUint32(20),
    colorType: view.getUint8(25),
  };
}
// Truecolour+alpha (6) or greyscale+alpha (4) -- either carries the alpha
// channel `film_transparent` asked Blender for.
const ALPHA_COLOR_TYPES = new Set([4, 6]);

async function renderMeshWithBlender(
  meshBytes: Uint8Array,
  options: Readonly<{
    width: number;
    height: number;
    seed: number;
    samples: number;
    blenderPath: string;
    run: CommandRunner;
    signal: AbortSignal;
  }>,
): Promise<Uint8Array> {
  const workspace = await mkdtemp(join(tmpdir(), "rvs-hi3dgen-"));
  try {
    const meshPath = join(workspace, "mesh.glb");
    const scriptPath = join(workspace, "render.py");
    const argsPath = join(workspace, "args.json");
    const outputPath = join(workspace, "render.png");
    await writeFile(meshPath, meshBytes);
    await writeFile(scriptPath, buildBlenderScript(), "utf8");
    await writeFile(
      argsPath,
      JSON.stringify({
        meshPath,
        outputPath,
        width: options.width,
        height: options.height,
        seed: options.seed,
        samples: options.samples,
      }),
      "utf8",
    );
    await options.run(
      options.blenderPath,
      [
        "--background",
        "--factory-startup",
        "--python",
        scriptPath,
        "--",
        argsPath,
      ],
      { cwd: workspace, signal: options.signal },
    );
    const png = await readFile(outputPath);
    const ihdr = readPngIhdr(png);
    if (
      !ihdr ||
      ihdr.width !== options.width ||
      ihdr.height !== options.height ||
      !ALPHA_COLOR_TYPES.has(ihdr.colorType)
    )
      throw new Error("HI3DGEN_RENDER_QC_FAILED");
    return png;
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
}

export function createSelfHosted3DMaterialProvider(
  config: SelfHosted3DMaterialProviderConfig,
): MaterialProvider {
  const baseUrl = config.baseUrl;
  const blenderPath = config.blenderPath ?? "blender";
  const samples = config.samples ?? BLENDER_SAMPLES;
  const client = config.client ?? defaultHi3DGenClient;
  const run = config.runCommand ?? runCommand;
  return {
    tool: HI3DGEN_BLENDER_TOOL,
    generate: async (request, signal) => {
      if (!baseUrl)
        throw new MaterialGenerationError(
          "MATERIAL_PROVIDER_NOT_CONFIGURED",
          request.assetId,
          "RVS_HI3DGEN_BASE_URL is not configured for this deployment",
        );
      const seed =
        request.seed ?? deriveMaterialSeed(request.assetId, request.prompt);
      const mesh = await client(
        baseUrl,
        { prompt: request.prompt, seed },
        signal,
      );
      const png = await renderMeshWithBlender(mesh, {
        width: request.canvas.width,
        height: request.canvas.height,
        seed,
        samples,
        blenderPath,
        run,
        signal,
      });
      const sha256 = createHash("sha256").update(png).digest("hex");
      return {
        bytes: png,
        contentType: "image/png" as const,
        provenance: {
          tool: HI3DGEN_BLENDER_TOOL,
          prompt: request.prompt,
          seed,
          sha256,
        },
      };
    },
  };
}
